In [1]:
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem, Descriptors
import pickle

In [2]:
df = pd.read_csv("Cleaned_SERT_Data.csv")
df.tail()

,Molecule ChEMBL ID,Smiles,Standard Type,Standard Value,pChEMBL Value,Molecular Weight,AlogP,label
5311,CHEMBL6051563,CNCc1cc(OCc2ccccc2Cl)n(CC2CCCC2)n1,Ki,1.8,8.74,333.86,4.03,1
5312,CHEMBL5962474,CNCc1cc(OCc2cc(F)ccc2F)n(Cc2ccc(Cl)cc2)n1,Ki,1.5,8.82,377.82,4.16,1
5313,CHEMBL5979654,CNCc1cc(OCc2ccccc2F)n(CC2CCCCC2)n1,Ki,1.6,8.80,331.44,3.90,1
5314,CHEMBL5783460,CNCc1cc(OCc2ccc(F)cc2Cl)n(CC2CCCCC2)n1,Ki,1.5,8.82,365.88,4.55,1
5315,CHEMBL5958084,CNCc1cc(OCc2cccc(Cl)c2)n(CC2OC3CCC2CC3)n1,Ki,8.1,8.09,375.90,3.79,1

In [3]:
fingerprint = []
for smile in df["Smiles"]:
    mol = Chem.MolFromSmiles(smile)
    morgan_fp = AllChem.GetMorganFingerprintAsBitVect(mol, radius=2, nBits=2048)
    fingerprint.append(list(morgan_fp))
fingerprint_df = pd.DataFrame(fingerprint, columns=[f'FP_{i}' for i in range(2048)])

[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:53] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator
[18:53:54] DEPRECATION WARNING: please use MorganGenerator

In [4]:
num_h_donors = []
num_h_acceptors = []
tpsa = []
num_rotatable_bonds = []
num_aromatic_rings = []
num_saturated_rings = []
num_aliphatic_rings = []
num_heteroatoms = []
mol_logp = []
num_rings = []
for smiles in df['Smiles']:
        mol = Chem.MolFromSmiles(smiles)
        num_h_donors.append(Descriptors.NumHDonors(mol))
        num_h_acceptors.append(Descriptors.NumHAcceptors(mol))
        tpsa.append(Descriptors.TPSA(mol))
        num_rotatable_bonds.append(Descriptors.NumRotatableBonds(mol))
        num_aromatic_rings.append(Descriptors.NumAromaticRings(mol))
        num_saturated_rings.append(Descriptors.NumSaturatedRings(mol))
        num_aliphatic_rings.append(Descriptors.NumAliphaticRings(mol))
        num_heteroatoms.append(Descriptors.NumHeteroatoms(mol))
        mol_logp.append(Descriptors.MolLogP(mol))
        num_rings.append(Descriptors.RingCount(mol))
desc_df = pd.DataFrame({
    'NumHDonors': num_h_donors,
    'NumHAcceptors': num_h_acceptors,
    'TPSA': tpsa,
    'NumRotatableBonds': num_rotatable_bonds,
    'NumAromaticRings': num_aromatic_rings,
    'NumSaturatedRings': num_saturated_rings,
    'NumAliphaticRings': num_aliphatic_rings,
    'NumHeteroatoms': num_heteroatoms,
    'MolLogP': mol_logp,
    'NumRings': num_rings
})
desc_df.head()

,NumHDonors,NumHAcceptors,TPSA,NumRotatableBonds,NumAromaticRings,NumSaturatedRings,NumAliphaticRings,NumHeteroatoms,MolLogP,NumRings
0,1,4,58.64,0,1,2,4,5,4.8690,5
1,0,2,23.06,5,3,0,0,4,5.5489,3
2,1,3,30.49,5,1,1,1,3,2.9465,2
3,0,2,12.47,4,1,1,1,2,3.2801,2
4,1,3,32.70,7,1,1,1,3,4.1560,2

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5316 entries, 0 to 5315
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Molecule ChEMBL ID  5316 non-null   object
 1   Smiles              5316 non-null   object
 2   Standard Type       5316 non-null   object
 3   Standard Value      5316 non-null   float64
 4   pChEMBL Value       5316 non-null   float64
 5   Molecular Weight    5316 non-null   float64
 6   AlogP               5316 non-null   float64
 7   label               5316 non-null   int64
dtypes: float64(4), int64(1), object(3)
memory usage: 332.4+ KB

In [6]:
desc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5316 entries, 0 to 5315
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   NumHDonors         5316 non-null   int64
 1   NumHAcceptors      5316 non-null   int64
 2   TPSA               5316 non-null   float64
 3   NumRotatableBonds  5316 non-null   int64
 4   NumAromaticRings   5316 non-null   int64
 5   NumSaturatedRings  5316 non-null   int64
 6   NumAliphaticRings  5316 non-null   int64
 7   NumHeteroatoms     5316 non-null   int64
 8   MolLogP            5316 non-null   float64
 9   NumRings           5316 non-null   int64
dtypes: float64(2), int64(8)
memory usage: 415.4 KB

In [7]:
fingerprint_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5316 entries, 0 to 5315
Columns: 2048 entries, FP_0 to FP_2047
dtypes: int64(2048)
memory usage: 83.1 MB

In [8]:
features = pd.concat([desc_df, fingerprint_df, df["Molecular Weight"], df["label"]], axis=1)
features.head()

,NumHDonors,NumHAcceptors,TPSA,NumRotatableBonds,NumAromaticRings,NumSaturatedRings,NumAliphaticRings,NumHeteroatoms,MolLogP,NumRings,...,FP_2040,FP_2041,FP_2042,FP_2043,FP_2044,FP_2045,FP_2046,FP_2047,Molecular Weight,label
0,1,4,58.64,0,1,2,4,5,4.8690,5,...,0,0,0,0,0,0,0,0,412.57,1
1,0,2,23.06,5,3,0,0,4,5.5489,3,...,0,0,0,0,0,0,0,0,391.36,0
2,1,3,30.49,5,1,1,1,3,2.9465,2,...,0,0,0,0,0,0,0,0,263.38,0
3,0,2,12.47,4,1,1,1,2,3.2801,2,...,0,0,0,0,0,0,0,0,247.38,0
4,1,3,32.70,7,1,1,1,3,4.1560,2,...,0,0,0,0,0,0,0,0,305.46,0

In [10]:
features.to_csv("Ready_Data.csv",index=False)