In [43]:
import pandas as pd
import numpy as np

In [44]:
df = pd.read_csv("rawDataSerotoninTransporter.csv", sep=";")
df.head()

,Molecule ChEMBL ID,Molecule Name,Molecule Max Phase,Molecular Weight,#RO5 Violations,AlogP,Compound Key,Smiles,Standard Type,Standard Relation,...,Document ChEMBL ID,Source ID,Source Description,Document Journal,Document Year,Cell ChEMBL ID,Properties,Action Type,Standard Text Value,Value
0,CHEMBL211372,NaN,NaN,412.57,0.0,4.87,5e,CN1C2CCC1C1COC(=O)CCCCCCCCC(=O)Nc3ccc(cc3)C1C2,Ki,'=',...,CHEMBL1137428,1,Scientific Literature,J Med Chem,2006.0,NaN,NaN,NaN,NaN,1.9
1,CHEMBL4085703,NaN,NaN,346.48,0.0,3.10,4b,COC1NN=C(C[S+]([O-])C(c2ccccc2)c2ccccc2)S1,IC50,NaN,...,CHEMBL4028886,1,Scientific Literature,J Med Chem,2017.0,CHEMBL3307715,NaN,NaN,NaN,NaN
2,CHEMBL4103632,NaN,NaN,328.46,0.0,3.88,4c,Cc1nnc(C[S+]([O-])C(c2ccccc2)c2ccccc2)s1,IC50,NaN,...,CHEMBL4028886,1,Scientific Literature,J Med Chem,2017.0,CHEMBL3307715,NaN,NaN,NaN,NaN
3,CHEMBL4077697,NaN,NaN,307.42,0.0,4.12,7b,[O-][S+](Cc1ccncc1)C(c1ccccc1)c1ccccc1,IC50,NaN,...,CHEMBL4028886,1,Scientific Literature,J Med Chem,2017.0,CHEMBL3307715,NaN,NaN,NaN,NaN
4,CHEMBL4080841,NaN,NaN,322.43,0.0,3.82,7j,Cc1cnc(C[S+]([O-])C(c2ccccc2)c2ccccc2)nc1,IC50,NaN,...,CHEMBL4028886,1,Scientific Literature,J Med Chem,2017.0,CHEMBL3307715,NaN,NaN,NaN,NaN

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9766 entries, 0 to 9765
Data columns (total 48 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Molecule ChEMBL ID          9766 non-null   object
 1   Molecule Name               2259 non-null   object
 2   Molecule Max Phase          1974 non-null   float64
 3   Molecular Weight            9736 non-null   float64
 4   #RO5 Violations             9604 non-null   float64
 5   AlogP                       9604 non-null   float64
 6   Compound Key                9766 non-null   object
 7   Smiles                      9662 non-null   object
 8   Standard Type               9766 non-null   object
 9   Standard Relation           7907 non-null   object
 10  Standard Value              7907 non-null   float64
 11  Standard Units              7929 non-null   object
 12  pChEMBL Value               7037 non-null   float64
 13  Data Validity Comment       110 non-null    object
 14  Comment                     3151 non-null   object
 15  Uo Units                    7929 non-null   object
 16  Ligand Efficiency BEI       6893 non-null   float64
 17  Ligand Efficiency LE        6837 non-null   float64
 18  Ligand Efficiency LLE       6837 non-null   float64
 19  Ligand Efficiency SEI       6834 non-null   float64
 20  Potential Duplicate         9766 non-null   int64
 21  Assay ChEMBL ID             9766 non-null   object
 22  Assay Description           9766 non-null   object
 23  Assay Type                  9766 non-null   object
 24  BAO Format ID               9766 non-null   object
 25  BAO Label                   9766 non-null   object
 26  Assay Organism              7039 non-null   object
 27  Assay Tissue ChEMBL ID      176 non-null    object
 28  Assay Tissue Name           176 non-null    object
 29  Assay Cell Type             5903 non-null   object
 30  Assay Subcellular Fraction  1758 non-null   object
 31  Assay Parameters            33 non-null     object
 32  Assay Variant Accession     68 non-null     object
 33  Assay Variant Mutation      68 non-null     object
 34  Target ChEMBL ID            9766 non-null   object
 35  Target Name                 9766 non-null   object
 36  Target Organism             9766 non-null   object
 37  Target Type                 9766 non-null   object
 38  Document ChEMBL ID          9766 non-null   object
 39  Source ID                   9766 non-null   int64
 40  Source Description          9766 non-null   object
 41  Document Journal            6671 non-null   object
 42  Document Year               8023 non-null   float64
 43  Cell ChEMBL ID              5334 non-null   object
 44  Properties                  199 non-null    object
 45  Action Type                 235 non-null    object
 46  Standard Text Value         1558 non-null   object
 47  Value                       7907 non-null   float64
dtypes: float64(12), int64(2), object(34)
memory usage: 3.6+ MB

In [46]:
df = df[df['Standard Relation'] == "'='"].copy()
df["Standard Relation"].unique()

array(["'='"], dtype=object)

Keeping only important features

In [47]:
numeric_columns = df.select_dtypes(include=['float64', 'int64']).columns
df[numeric_columns].corr()

,Molecule Max Phase,Molecular Weight,#RO5 Violations,AlogP,Standard Value,pChEMBL Value,Ligand Efficiency BEI,Ligand Efficiency LE,Ligand Efficiency LLE,Ligand Efficiency SEI,Potential Duplicate,Source ID,Document Year,Value
Molecule Max Phase,1.000000,0.027015,-0.052494,0.100217,0.003701,0.043034,-0.073788,-0.162449,-0.046667,0.071785,0.063675,-0.094793,-0.049859,0.023522
Molecular Weight,0.027015,1.000000,0.647334,0.575346,-0.048974,0.012990,-0.738754,-0.696663,-0.395090,-0.256335,-0.074394,-0.059856,0.035950,-0.022553
#RO5 Violations,-0.052494,0.647334,1.000000,0.715660,-0.022266,-0.087736,-0.493142,-0.468458,-0.574167,-0.021842,-0.056993,-0.064018,0.033195,-0.009260
AlogP,0.100217,0.575346,0.715660,1.000000,-0.014187,0.023805,-0.440672,-0.404092,-0.695758,0.128117,-0.033879,0.017356,0.064302,-0.051275
Standard Value,0.003701,-0.048974,-0.022266,-0.014187,1.000000,-0.439523,-0.241133,-0.241116,-0.275827,-0.060210,-0.013932,-0.027609,-0.032992,0.058222
pChEMBL Value,0.043034,0.012990,-0.087736,0.023805,-0.439523,1.000000,0.562792,0.572982,0.693783,0.100972,0.101888,-0.005388,-0.006158,-0.393118
Ligand Efficiency BEI,-0.073788,-0.738754,-0.493142,-0.440672,-0.241133,0.562792,1.000000,0.955208,0.722758,0.299736,0.109521,-0.012045,-0.048632,-0.209662
Ligand Efficiency LE,-0.162449,-0.696663,-0.468458,-0.404092,-0.241116,0.572982,0.955208,1.000000,0.702994,0.304601,0.101495,-0.004418,-0.065468,-0.209778
Ligand Efficiency LLE,-0.046667,-0.395090,-0.574167,-0.695758,-0.275827,0.693783,0.722758,0.702994,1.000000,-0.019775,0.098311,-0.022445,-0.057376,-0.230605
Ligand Efficiency SEI,0.071785,-0.256335,-0.021842,0.128117,-0.060210,0.100972,0.299736,0.304601,-0.019775,1.000000,0.031300,-0.028494,-0.039110,-0.044682
Potential Duplicate,0.063675,-0.074394,-0.056993,-0.033879,-0.013932,0.101888,0.109521,0.101495,0.098311,0.031300,1.000000,0.130312,0.117891,-0.021573
Source ID,-0.094793,-0.059856,-0.064018,0.017356,-0.027609,-0.005388,-0.012045,-0.004418,-0.022445,-0.028494,0.130312,1.000000,0.603330,0.019992
Document Year,-0.049859,0.035950,0.033195,0.064302,-0.032992,-0.006158,-0.048632,-0.065468,-0.057376,-0.039110,0.117891,0.603330,1.000000,-0.008552
Value,0.023522,-0.022553,-0.009260,-0.051275,0.058222,-0.393118,-0.209662,-0.209778,-0.230605,-0.044682,-0.021573,0.019992,-0.008552,1.000000

In [50]:
important = ["Molecule ChEMBL ID", "Smiles", "Standard Type", "Standard Value", "pChEMBL Value", "Molecular Weight", "AlogP"]
df = df[important]
df.head()

,Molecule ChEMBL ID,Smiles,Standard Type,Standard Value,pChEMBL Value,Molecular Weight,AlogP
0,CHEMBL211372,CN1C2CCC1C1COC(=O)CCCCCCCCC(=O)Nc3ccc(cc3)C1C2,Ki,1.9,8.72,412.57,4.87
7,CHEMBL4076722,[O-][S+](Cc1csc(Br)c1)C(c1ccccc1)c1ccccc1,IC50,44700.0,4.35,391.36,5.55
9,CHEMBL257083,CNCC1CCCCC1(OC)c1cccc(OC)c1,IC50,2686.0,5.57,263.38,2.95
10,CHEMBL258336,CO[C@]1(c2ccccc2)CCCC[C@@H]1CN(C)C,IC50,2534.0,5.60,247.38,3.28
11,CHEMBL270570,CCCCO[C@]1(c2cccc(O)c2)CCCC[C@@H]1CN(C)C,IC50,2744.0,5.56,305.46,4.16

Handeling null values

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7109 entries, 0 to 9765
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Molecule ChEMBL ID  7109 non-null   object
 1   Smiles              7075 non-null   object
 2   Standard Type       7109 non-null   object
 3   Standard Value      7109 non-null   float64
 4   pChEMBL Value       7037 non-null   float64
 5   Molecular Weight    7109 non-null   float64
 6   AlogP               7053 non-null   float64
dtypes: float64(4), object(3)
memory usage: 444.3+ KB

In [53]:
df_noNull = df.dropna()
df_noNull.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6981 entries, 0 to 9765
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Molecule ChEMBL ID  6981 non-null   object
 1   Smiles              6981 non-null   object
 2   Standard Type       6981 non-null   object
 3   Standard Value      6981 non-null   float64
 4   pChEMBL Value       6981 non-null   float64
 5   Molecular Weight    6981 non-null   float64
 6   AlogP               6981 non-null   float64
dtypes: float64(4), object(3)
memory usage: 436.3+ KB

Creating label using pChEMBL value

In [58]:
df_filtered = df_noNull.copy()
df_filtered["label"] = (df_noNull['pChEMBL Value'] >= 6).astype(int)
df_filtered.head()

,Molecule ChEMBL ID,Smiles,Standard Type,Standard Value,pChEMBL Value,Molecular Weight,AlogP,label
0,CHEMBL211372,CN1C2CCC1C1COC(=O)CCCCCCCCC(=O)Nc3ccc(cc3)C1C2,Ki,1.9,8.72,412.57,4.87,1
7,CHEMBL4076722,[O-][S+](Cc1csc(Br)c1)C(c1ccccc1)c1ccccc1,IC50,44700.0,4.35,391.36,5.55,0
9,CHEMBL257083,CNCC1CCCCC1(OC)c1cccc(OC)c1,IC50,2686.0,5.57,263.38,2.95,0
10,CHEMBL258336,CO[C@]1(c2ccccc2)CCCC[C@@H]1CN(C)C,IC50,2534.0,5.60,247.38,3.28,0
11,CHEMBL270570,CCCCO[C@]1(c2cccc(O)c2)CCCC[C@@H]1CN(C)C,IC50,2744.0,5.56,305.46,4.16,0

In [59]:
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6981 entries, 0 to 9765
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Molecule ChEMBL ID  6981 non-null   object
 1   Smiles              6981 non-null   object
 2   Standard Type       6981 non-null   object
 3   Standard Value      6981 non-null   float64
 4   pChEMBL Value       6981 non-null   float64
 5   Molecular Weight    6981 non-null   float64
 6   AlogP               6981 non-null   float64
 7   label               6981 non-null   int64
dtypes: float64(4), int64(1), object(3)
memory usage: 490.9+ KB

In [65]:
df_filtered["Smiles"].nunique()

5316

In [66]:
df_filtered = df_filtered.drop_duplicates(subset="Smiles", keep="first")
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5316 entries, 0 to 9761
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Molecule ChEMBL ID  5316 non-null   object
 1   Smiles              5316 non-null   object
 2   Standard Type       5316 non-null   object
 3   Standard Value      5316 non-null   float64
 4   pChEMBL Value       5316 non-null   float64
 5   Molecular Weight    5316 non-null   float64
 6   AlogP               5316 non-null   float64
 7   label               5316 non-null   int64
dtypes: float64(4), int64(1), object(3)
memory usage: 373.8+ KB

In [67]:
df_filtered.to_csv("Cleaned_SERT_Data.csv",index=False)